### ISSUE TITLE
question(defer): defer Mermaid

### ISSUE THREAD

**Issue by Kristinita** [shinsenter/defer.js#111]
### 1. Summary

I failed to use Defer.js with [**Mermaid.js**](https://mermaid-js.github.io/mermaid/#/) — JavaScript diagramming and charting tool.

It would be nice, if you tell me how to use Defer.js for Mermaid.

#### 2.1. Sources

[**Sources**](https://replit.com/@Kristinita/KiraMermaid-MCVE) for the simple Mermaid pie chart on Repl.it.

1. `index.html`:

	```html
	<!doctype html>
	<html lang="en">
		<head>
			<meta charset="utf-8">
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<title>Kira Mermaid MCVE</title>
			<script src="https://cdn.jsdelivr.net/npm/@shinsenter/defer.js/dist/defer_plus.min.js"></script>
			<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js" defer></script>
			<script src="mermaid.js" defer></script>
		</head>
		<body>
			<pre class="mermaid">
			pie showData
				title Who is Kira?
				"Goddess": 1
			</pre>
		</body>
	</html>

	```

1. `mermaid.js`:

	```js
	mermaid.initialize({ startOnLoad: true });

	```

#### 2.2. Result

[**Demonstration**](https://kiramermaid-mcve.kristinita.repl.co/) on Repl.it:

![Kira Goddess pie chart on Mermaid](https://i.imgur.com/HJvlTtA.png)

I can’t get the same result with Defer.js.

### 3. Not helped

I read [**Mermaid API usage**](https://mermaid-js.github.io/mermaid/#/usage) and tried variants below. None helped me.

#### 3.1. 2 Defer.js() functions

```js
Defer.js('https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js', 'mermaid', 1000);
Defer.js('mermaid.js', 'mermaid-local', 2000);
```

#### 3.2. Defer.all()

```html
<script type="kiramermaid" src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
<script type="kiramermaid" src="mermaid.js"></script>

<script>
	Defer.all('script[type="kiramermaid"]', 1000);
</script>
```

#### 3.3. mermaid.initialize()

```js
Defer.js('https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js', 'mermaid', 1000, function()
	{ mermaid.initialize({ startOnLoad: true });});
```

#### 3.4. mermaid.initialize() without options

```js
Defer.js('https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js', 'mermaid', 1000, function()
	{ mermaid.initialize({});});
```

#### 3.5. mermaid.init()

```js
Defer.js('https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js', 'mermaid', 1000, function()
	{ mermaid.init({});});
```

#### 3.6. mermaid.initialize() after DOMContentLoaded event

```js
Defer.js('https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js', 'mermaid', 1000, function()
	{ document.addEventListener('DOMContentLoaded', _ => new mermaid.initialize({ startOnLoad: true }));});
```

#### 3.7. mermaid.init() after DOMContentLoaded event

```js
Defer.js('https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js', 'mermaid', 1000, function()
	{ document.addEventListener('DOMContentLoaded', _ => new mermaid.init());});
```

Thanks.

**Comment by shinsenter** [comment]
Hey @Kristinita 

Thank you for your question, and I would like to answer your question.

After going through the source code of Mermaid.js, I think that initializing Mermaid.js after lazy loading it just doesn't work. 

As they also mention on the official [documentation page](https://mermaid-js.github.io/mermaid/#/usage?id=calling-mermaidinit), it says:

> By default, `mermaid.init` will be called when the document is ready, finding all elements with `class="mermaid"`.

So, that means after lazy loading the Mermaid.js library (meaning you load it after the web page has finished loading), you need to manually initialize Mermaid.

You can view the source code for the [`mermaid.initialize` here](https://github.com/mermaid-js/mermaid/blob/develop/src/mermaid.js#L143-L156), and I found it is used to set the options for the library.

Besides, the actual function used to initialize Mermaid.js is `mermaid.init`, you can [check the source code here](https://github.com/mermaid-js/mermaid/blob/2cc88df08a32fa9e1e86bbf72cc2a6faf717b55c/src/mermaid.js#L162-L193), and the [documentation about it](https://mermaid-js.github.io/mermaid/#/usage?id=calling-mermaidinit) here.

Therefore, your lazy loading methods from 3.1 to 3.7 (excepts 3.5) will not work if you use the `mermaid.initialize` function (because the `mermaid.init` function is not called).

## About your setups

### 3.1. 2 Defer.js() functions
Scripts lazy loaded usign the `Defer.js` are asynchronous, the order of executions is not guaranteed, we cannot conclude that the Mermaid library is presented when the `mermaid.min.js` executed.

### 3.2. Defer.all()
In this case, the order of executions is guaranteed, but the `mermaid.initialize` does not init the library.

### 3.3. mermaid.initialize()
The `mermaid.initialize` does not init the library.

### 3.4. mermaid.initialize() without options
The `mermaid.initialize` does not init the library.

### 3.5. mermaid.init()
I have no idea why it didn't work. Can I have your full setup? 
I made one here, and it actually worked: https://jsfiddle.net/nodmtpbf/

### 3.6. mermaid.initialize() after DOMContentLoaded event
The DOMContentLoaded event has already been triggered before the script is dowloaded, so the callback function will not be called.

### 3.7. mermaid.init() after DOMContentLoaded event
The DOMContentLoaded event has already been triggered before the script is dowloaded, so the callback function will not be called.

## Working setup
https://jsfiddle.net/nodmtpbf/

```html
<script src="https://cdn.jsdelivr.net/npm/@shinsenter/defer.js@3.1.0/dist/defer_plus.min.js"></script>
<script>
    Defer.js('https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js', 'mermaid', 0, function() {
        mermaid.init();
    });
</script>
```

**Comment by Kristinita** [comment]
**Status: CONFIRMED** :heavy_check_mark:

Your setup works for me for MCVE and real Mermaid charts.

It looks like I made a mistake by adding {braces}:

```diff
+ mermaid.init();
- mermaid.init({});
```

(And I don’t think 2 different functions with names `mermaid.init()` and `mermaid.initialize()` is the best practice.)

Sorry for taking your time.

Thanks.

**Comment by shinsenter** [comment]
@Kristinita 
Good to see your problem solved.
Have a nice day!

If you find this library helpful, please give me a star on Github or consider supporting me so I can continue to create other open source projects.
