### ISSUE TITLE
preload hints?

### ISSUE THREAD

**Issue by peixotorms** [shinsenter/defer.js#112]
Hi there, when using this script with several js files, I noticed that they are downloaded in a sequential manner, one after the other instead of simultaneously. 

I understand we can preload them, but that would defeat the purpose when using the delay until interaction option.

Cloudflare's Rocket Loader feature had a similar issue during early stages of development, and they sorted it by adding preload hints.
I suggest looking at this article, under "Taming the Waterfall".
https://blog.cloudflare.com/too-old-to-rocket-load-too-young-to-die/

Would it be possible to do the same on your script, by adding preload hints before actually starting to transform the html and loading the script, for deferred scripts?

Ideally, for defer and delay scripts should include their own hints separately.

CF Rocket Loader source:
https://gist.github.com/peixotorms/f48cfb8f104a292c3267f699524f0e48

Thanks

**Comment by shinsenter** [comment]
@peixotorms 

Thank you for the ideas as well as links for easy reference.

I also had similar experiences when doing page speed optimization for my previous projects.  And I think with current web technology, the combination of defer and preload hints is probably the most effective option.

Regarding the Defer.js library, my ultimate goal is to create a library that is as compact as possible, but still ensures its main function: defer of loading of the resources.

Since the library is written entirely in JavaScript and can only be run on the client's browser side, I think it should be limited to changing the original HTML structure of the server side. Of course, a tiny library cannot meet all the needs of many different websites, so I decided to leave the optimization at the HTML generation step to the website owner. They can apply preload hints etc if they want a more dramatic result, like the one you suggested.

I also have an open source PHP library that allows the server side to automatically change the HTML structure of the web page before it is sent to the browser. You can refer to it here: https://code.shin.company/defer.php

Finally, if you have any ideas on how to do something, I'd love to get your input by making a pull request. I would be more than happy to accept it if it were lean.

Regards.

**Comment by peixotorms** [comment]
Well, I managed to add the preloading with javascript, by adding extra code.

**Comment by shinsenter** [comment]
@peixotorms 
I got your idea, I am thinking of a smart way to implement it without adding too much code to the library.

By the way, I noticed that on Chrome and Safari (macOS) browsers automatically preload resources without preload hints, custom script tags just got preloaded before the type attribute changes.

**Comment by shinsenter** [comment]
@peixotorms 
I released v3.2 with preload hints feature added. Please make a look at the latest version.

**Comment by peixotorms** [comment]
Thanks a lot, I can confirm it's working as intended

**Comment by shinsenter** [comment]
@peixotorms Good to hear that. Thank you for the idea.
