### ISSUE TITLE
sitemap issues

### ISSUE THREAD

**Issue by ps2master** [shinsenter/defer.js#125]
Hey, I'm having some issues with Google indexing my sitemaps when this plugin is active, not sure if anyone has reported it but I had the plugin switched off for a few days and Google indexed my sitemaps on search console fine.

24 hours later, I activated the plugin again and the sitemaps were not indexed by Google search console.

I have now disabled all optimising options, except the lazy load for images, because it works great, just to see if Google will do the exact same thing, I think it will, because I have another problem with Yoast SEO when I try to optimise my newest content manually, I am getting the error that's shown below:

```
<!DOCTYPE html>
<html class="no-deferjs">
<head><meta name="generator" content="[defer.php](https://code.shin.company/defer.php)"></head>
<body><p>{"objects":[],"next_url":false}</p></body>
<!--
site name
-->
</html>
```

Could you please advise on what this issue might be as I love the plugin and its optimisation features and it has been working fine for me for years, until the 20th of August this year when everything just went downhill?

**Comment by shinsenter** [comment]
@ps2master 
Thank you for reaching out. Could I have more specific information about the error you believe my plugin is causing? Regarding the HTML snippet you've posted and consider it an error message, it's challenging for me to pinpoint the cause since you haven't provided me with the complete HTML of the webpage.

Can I please request two full HTML versions of your website, one with my plugin enabled and one with it disabled? If it's related to the content of the sitemap.xml file, I also need to know which plugin you're using to generate the sitemap.xml, as well as the contents of the sitemap.xml file when it's generated with my plugin enabled and disabled. I need to compare the differences and provide a more accurate assessment of your issue.

By the way, this is the place to discuss issues related to my WordPress plugin.
https://github.com/shinsenter/defer-wordpress/issues
If you don't mind, please create an Issue here and provide me with more details about your problem.

Best regards

**Comment by shinsenter** [comment]
@ps2master 

I've just released a new version of the plugin. Would you mind taking a look to see if it can address your issue? Your feedback is greatly appreciated.

If you find this plugin valuable, please consider leaving a [5-star review (⭐️⭐️⭐️⭐️⭐️)](https://wordpress.org/support/plugin/shins-pageload-magic/reviews/?filter=5#new-post).

Best regards.

**Comment by ps2master** [comment]
Hey, just installed the new update, ran my usual Yeast SEO optimisations and the error was gone, thank you! I will just wait for Google to index the sitemaps again now and will report back.

**Comment by ps2master** [comment]
Sitemaps are also indexing without problems again, thank you for being so efficient and fixing the issues so quickly.
