### ISSUE TITLE
javascript loaded but not function anything

### ISSUE THREAD

**Issue by reedniv** [shinsenter/defer.js#76]
`<script src='//code.jquery.com/jquery-3.1.1.min.js?speed=1' type='text/javascript'/>`

work fine if I'll use this code but after change to

`<script>Defer.js('https://code.jquery.com/jquery-3.1.1.min.js', 'jquery-js', 3000);</script>` not work, just javascript loaded but not function.

**Comment by shinsenter** [comment]
Hey @reedniv 

`<script>Defer.js('https://code.jquery.com/jquery-3.1.1.min.js', 'jquery-js', 3000);</script>`

Your code means "please defer loading `https://code.jquery.com/jquery-3.1.1.min.js` after 3 seconds since the page has completely loaded."

Hence any script that calls to jQuery's methods (including the $ symbol) before jQuery library is loaded will be inoperable due to the lack of jQuery library.

You can try to reduce or remove the timeout value in the third parameter of `Defer.js()`.  Or try calling jQuery functions later than when jQuery is loaded.
